### PR TITLE
Updated Mississippi River Pipeline + compressor stations

### PR DESCRIPTION
**Pull request by charmainegem**

### CODE REVIEW

**Comment by bairdlangenbrunner** [comment]
Hi Charmaine, the pipeline file looks great here but I've realized I have been opening up the compressor station data in QGIS rather than geojson, and QGIS does some more automatic handling of things, so I've missed some small differences to the compressor station files that I'd like us to update if we can!

Looking into the compressor station file a bit more, I see the lat/lons are in a different projection for this file — in this case, EPSG 3857. Looks like this is a [typical coordinate reference system](https://epsg.io/3857) for some of the tools we're using. You can see this quickly in the geojson file text (`"crs"` toward the top), and the lat/lon values are really wonky looking, e.g. in line 6:

```
{ "type": "Point", "coordinates": [ -10032697.908767700195312, 4676244.073529469780624 ] } }
```

Do you mind trying to fix the file on your end, and resubmitting it here? One way to do it is to open it up in QGIS and export it again as a geojson with the WGS84 (same as EPSG 4326) projection. Once you do, you can push that updated file to the [`charmaine-P0162`](https://github.com/GlobalEnergyMonitor/GOIT-GGIT-pipeline-routes/tree/charmaine-P0162) branch (no need to submit another pull request, it will carry over from this one).

Also when you export other ProjectID compressor station files from now on, try to double-check that the WGS84/EPSG 4326 projection is being used. Definitely pretty easy to change them later, of course, so not a big deal that it went unnoticed earlier. I am trying to keep everything in the same projection, and the geojson file specification says [they use WGS84](https://datatracker.ietf.org/doc/html/rfc7946#section-4).

During our coworking session tomorrow, let's take a look at other compressor station files together and make sure they're looking good.

**Comment by charmainegem** [comment]
Thanks for the heads up, I'll be sure to double check from now on! I just fixed it, so I'll re-upload rn

**Comment by bairdlangenbrunner** [comment]
Thanks for doing that! Will take a look and merge shortly.

**Review by bairdlangenbrunner — APPROVED** [review]
perfect!

**Pull request merged**
